# Generated by Django 4.2.2 on 2023-06-23 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='course',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='department',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
